spring.application.name=rag-arch
server.port=8080

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=rag-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

rag.retrieval.top-k=5
rag.data-path=classpath:rag-data
rag.chunk.size=500
rag.chunk.overlap=50

embedding.endpoint=http://localhost:8081
embedding.max-chunk-tokens=512
embedding.chunk-overlap-tokens=50

embedding.service.url=http://localhost:8000

rag.indexing.data-path: D:/From-C-Drive/Weekly-Architecture-India-Tasks-Status/Tech-Task/RAG-Architecture/Data-For-POC/rag-arch/src/main/resources/rag-data/kubernetes/

qdrant.url=http://localhost:6333


llm.service.url: http://localhost:11434
llm.service.model: llama3

